-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE lead (
    id SERIAL PRIMARY KEY,
    name text,
    phonenumber text,
    address text,
    email text,
    tasks json
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX lead_pkey ON lead(id int4_ops);
